version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: havirkesht_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: havirkesht
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Reza2009
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    restart: always
    container_name: havirkesht_web
    environment:
      - ALLOWED_HOSTS=185.252.86.18,rezadalvand.ir
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=havirkesht
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=Reza2009
#    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: